Fix pre-commit errors that were missed initially
toolforge/buildpack-admission-controller pull request #22
Opened 2023-02-02 00:11 UTC by NdibeRaymond

Bug: https://phabricator.wikimedia.org/T325184

2023-02-02 12:37 UTC, david-caro requested changes
Just the exitting when an error happens, the rest is good :+1:

2023-02-02 12:37 UTC, david-caro commented on main.go
> +		logrus.Errorln(err)
I think that here we should also `logrus.Exit(1)`,  so the program stops, otherwise it might get null pointer when trying to get to the config settings below.

2023-02-02 12:37 UTC, david-caro commented on main.go
> +		logrus.Errorln(err)
Probably here too, though currently just finishes, it makes sense to force a return code != 0

2023-02-02 12:37 UTC, david-caro commented on utils/realize_patch.sh
> +    # shellcheck disable=SC2044
nit: can you add to the comment "For loops over find output are fragile - we never are going to have enough templates"

2023-02-02 17:52 UTC, NdibeRaymond commented on utils/realize_patch.sh
> +    # shellcheck disable=SC2044
> nit: can you add to the comment "For loops over find output are fragile - we never are going to have enough templates"

what does "we never are going to have enough templates" mean in this context?

2023-02-06 16:14 UTC, david-caro commented on utils/realize_patch.sh
> +    # shellcheck disable=SC2044
So this file what it does, is find any template (*.tpl files) and "realizing" them, that means generating the file the template defines with the variables resolved.

This specific command looks under the current directory for those templates, so using something more performant or that will not break when there's many many matches is not really a concern, as there will never be many template files.

Does that reply your question? (we can have a quick chat if you prefer)

2023-02-06 16:50 UTC, NdibeRaymond commented on utils/realize_patch.sh
> +    # shellcheck disable=SC2044
Yes @david-caro It's clear now, thanks for taking your time to explain

2023-02-06 16:52 UTC, NdibeRaymond commented
Now that has been resolved I'm merging this

2023-02-06 16:52 UTC, merged